-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 08:54:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema teletfuego
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teletfuego
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teletfuego` DEFAULT CHARACTER SET utf8mb4 ;
USE `teletfuego` ;

-- -----------------------------------------------------
-- Table `teletfuego`.`importador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`importador` (
  `idImportador` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idImportador`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teletfuego`.`operarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`operarios` (
  `idOperario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_operario` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idOperario`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teletfuego`.`piezas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`piezas` (
  `idPieza` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_Pieza` VARCHAR(20) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `idImportador` INT(11) NULL DEFAULT NULL,
  `idOperario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idPieza`),
  INDEX `idImportador` (`idImportador` ASC) VISIBLE,
  INDEX `idOperario` (`idOperario` ASC) VISIBLE,
  CONSTRAINT `piezas_ibfk_1`
    FOREIGN KEY (`idImportador`)
    REFERENCES `teletfuego`.`importador` (`idImportador`),
  CONSTRAINT `piezas_ibfk_2`
    FOREIGN KEY (`idOperario`)
    REFERENCES `teletfuego`.`operarios` (`idOperario`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teletfuego`.`confecciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`confecciones` (
  `idConfeccion` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `idOperario` INT(11) NULL DEFAULT NULL,
  `idPieza` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idConfeccion`),
  INDEX `idPieza` (`idPieza` ASC) VISIBLE,
  INDEX `idOperario` (`idOperario` ASC) VISIBLE,
  CONSTRAINT `confecciones_ibfk_1`
    FOREIGN KEY (`idPieza`)
    REFERENCES `teletfuego`.`piezas` (`idPieza`),
  CONSTRAINT `confecciones_ibfk_2`
    FOREIGN KEY (`idOperario`)
    REFERENCES `teletfuego`.`operarios` (`idOperario`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teletfuego`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`facturas` (
  `idFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `numero` INT(10) NULL DEFAULT NULL,
  `idPieza` INT(11) NULL DEFAULT NULL,
  `idImportador` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `idImportador` (`idImportador` ASC) VISIBLE,
  INDEX `idPieza` (`idPieza` ASC) VISIBLE,
  CONSTRAINT `facturas_ibfk_1`
    FOREIGN KEY (`idImportador`)
    REFERENCES `teletfuego`.`importador` (`idImportador`),
  CONSTRAINT `facturas_ibfk_2`
    FOREIGN KEY (`idPieza`)
    REFERENCES `teletfuego`.`piezas` (`idPieza`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teletfuego`.`televisores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`televisores` (
  `idTelevisores` INT(11) NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`idTelevisores`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `teletfuego`.`mapas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teletfuego`.`mapas` (
  `idMapa` INT(11) NOT NULL AUTO_INCREMENT,
  `ubicacion` INT(10) NULL DEFAULT NULL,
  `orden` INT(10) NULL DEFAULT NULL,
  `idPieza` INT(11) NULL DEFAULT NULL,
  `idTelevisores` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idMapa`),
  INDEX `idPieza` (`idPieza` ASC) VISIBLE,
  INDEX `idTelevisores` (`idTelevisores` ASC) VISIBLE,
  CONSTRAINT `mapas_ibfk_1`
    FOREIGN KEY (`idPieza`)
    REFERENCES `teletfuego`.`piezas` (`idPieza`),
  CONSTRAINT `mapas_ibfk_2`
    FOREIGN KEY (`idTelevisores`)
    REFERENCES `teletfuego`.`televisores` (`idTelevisores`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
